In [14]:
import pandas as pd
import glob

# getting the location of excel files to be merged
input_path = 'C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Project Excel Files'

# read all the files with extension .xlsx i.e. excel 
filenames = glob.glob(input_path + "\*.xlsx")
print('Name and location of the files which are used for aggregation are:\n\n',filenames)

# empty data frame for the new output excel file with the merged excel files
consolidated_data = pd.DataFrame()

# for loop to iterate all excel files
for file in filenames:
   # using concat for excel files
   # after reading them with read_excel()
   df = pd.concat(pd.read_excel( file, sheet_name=None), ignore_index=True, sort=False)

   # appending data of excel files
   consolidated_data = consolidated_data.append( df, ignore_index=True)

print('\nConsolidated excel sheet now generated at the same location')
consolidated_data.to_excel("C:\\Users\\admin\\OneDrive\\Desktop\\Consolidated Data.xlsx", index=False)

Name and location of the files which are used for aggregation are:

 ['C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Project Excel Files\\2013 Dataset.xlsx', 'C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Project Excel Files\\2014 Dataset.xlsx', 'C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Project Excel Files\\2015 Dataset.xlsx', 'C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Project Excel Files\\2016 Dataset.xlsx', 'C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Project Excel Files\\2017 Dataset.xlsx', 'C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Project Excel Files\\2018 Dataset.xlsx', 'C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Project Excel Files\\2019 Dataset.xlsx', 'C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Project Excel Files\\2020 Dataset.xlsx']

Consolidated excel sheet now generated at the same location

In [4]:
dataset_df = pd.read_excel('C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\Consolidated Data.xlsx')

In [5]:
dataset_df.head()

,YEAR,AUTHORISATION ID / PERMIT ID,OPERATOR NAME,SITE ADDRESS,SITE POSTCODE,EA AREA NAME,ROUTE NAME,SUBSTANCE NAME,REPORTING THRESHOLD (kg),QUANTITY RELEASED (kg),ABOVE THRESHOLD,REGULATED INDUSTRY SECTOR,REGULATED INDUSTRY SUB SECTOR
0,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Benzo(a)pyrene,1.000,0.0,0.0,Water Industry,Water Industry
1,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Benzo(b)fluoranthene,1.000,0.0,0.0,Water Industry,Water Industry
2,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Octylphenols and octylphenol ethoxylates,1.000,0.0,0.0,Water Industry,Water Industry
3,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Air,Chloroform (Trichloromethane),100.000,0.0,0.0,Water Industry,Water Industry
4,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Trifluralin,0.001,0.0,0.0,Water Industry,Water Industry

In [6]:
dataset_df['QUANTITY RELEASED (kg)'] = dataset_df['QUANTITY RELEASED (kg)'].replace('below reporting threshold', 0.0)
dataset_df['QUANTITY RELEASED (kg)'] = dataset_df['QUANTITY RELEASED (kg)'].replace('Below Reporting Threshold', 0.0)

In [7]:
dataset_df['ABOVE THRESHOLD'] = 0

In [8]:
consolidated_data = consolidated_data.append( df, ignore_index=True)
print('Final Excel sheet now generated at the same location:')
consolidated_data.to_excel("C:\\Users\\admin\\OneDrive\\Desktop\\Consolidated Data.xlsx", index=False)

Final Excel sheet now generated at the same location:

In [9]:
dataset_df.head(30)

,YEAR,AUTHORISATION ID / PERMIT ID,OPERATOR NAME,SITE ADDRESS,SITE POSTCODE,EA AREA NAME,ROUTE NAME,SUBSTANCE NAME,REPORTING THRESHOLD (kg),QUANTITY RELEASED (kg),ABOVE THRESHOLD,REGULATED INDUSTRY SECTOR,REGULATED INDUSTRY SUB SECTOR
0,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Benzo(a)pyrene,1.000000e+00,0.000,0,Water Industry,Water Industry
1,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Benzo(b)fluoranthene,1.000000e+00,0.000,0,Water Industry,Water Industry
2,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Octylphenols and octylphenol ethoxylates,1.000000e+00,0.000,0,Water Industry,Water Industry
3,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Air,Chloroform (Trichloromethane),1.000000e+02,0.000,0,Water Industry,Water Industry
4,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Trifluralin,1.000000e-03,0.000,0,Water Industry,Water Industry
5,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Carbon tetrachloride (Tetrachloromethane),1.000000e+00,0.000,0,Water Industry,Water Industry
6,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Chloroform (Trichloromethane),5.000000e+00,0.000,0,Water Industry,Water Industry
7,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Air,Carbon dioxide,1.000000e+07,0.000,0,Water Industry,Water Industry
8,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Dichloromethane (DCM) (Methylene chloride),1.000000e+01,0.000,0,Water Industry,Water Industry
9,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Organotin compounds - as Sn,5.000000e+00,0.000,0,Water Industry,Water Industry
10,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Phenols - total as C,2.000000e+01,0.000,0,Water Industry,Water Industry
11,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Lead,2.000000e+01,0.000,0,Water Industry,Water Industry
12,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Dioxins and furans (PCDDs/PCDFs) - as WHO TEQ,1.000000e-04,0.000,0,Water Industry,Water Industry
13,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Dioxins and furans (PCDDs/PCDFs) - as ITEQ,1.000000e-04,0.000,0,Water Industry,Water Industry
14,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Air,Ammonia,1.000000e+03,0.000,0,Water Industry,Water Industry
15,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,"Brominated diphenylethers - penta-, octa- and ...",1.000000e-01,0.000,0,Water Industry,Water Industry
16,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Chlorides - as Cl,2.000000e+06,0.000,0,Water Industry,Water Industry
17,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Air,Methane,1.000000e+04,0.000,0,Water Industry,Water Industry
18,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Nonylphenols and nonylphenol ethoxylates,1.000000e+00,41.000,0,Water Industry,Water Industry
19,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Naphthalene,1.000000e+00,17.100,0,Water Industry,Water Industry
20,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Tributyltin and compounds - as TBT,5.000000e-03,0.011,0,Water Industry,Water Industry
21,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Mercury,1.000000e-01,0.420,0,Water Industry,Water Industry
22,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Nickel,2.000000e+01,382.000,0,Water Industry,Water Industry
23,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Cyanides - as CN,5.000000e+01,163.000,0,Water Industry,Water Industry
24,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Fluorides - as F,2.000000e+03,3640.000,0,Water Industry,Water Industry
25,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Zinc,1.000000e+02,977.000,0,Water Industry,Water Industry
26,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Di(2-ethylhexyl)phthalate (DEHP),1.000000e-01,29.700,0,Water Industry,Water Industry
27,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Diuron,5.000000e-02,1.550,0,Water Industry,Water Industry
28,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Halogenated organic compounds - as AOX,1.000000e+03,1730.000,0,Water Industry,Water Industry
29,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Nitrogen - as total N,5.000000e+04,335000.000,0,Water Industry,Water Industry

In [10]:
temp_list = []
for index, row in dataset_df.iterrows():
#    print(row['QUANTITY RELEASED (kg)'])
    #print(row['QUANTITY RELEASED (kg)'],row['REPORTING THRESHOLD (kg)'])
    if row['QUANTITY RELEASED (kg)'] > row['REPORTING THRESHOLD (kg)']:
        value = row['QUANTITY RELEASED (kg)'] - row['REPORTING THRESHOLD (kg)']
        temp_list.append(value)
    else:
        temp_list.append(0.0)

In [11]:
dataset_df['ABOVE THRESHOLD'] = temp_list

In [12]:
dataset_df.head(30)

,YEAR,AUTHORISATION ID / PERMIT ID,OPERATOR NAME,SITE ADDRESS,SITE POSTCODE,EA AREA NAME,ROUTE NAME,SUBSTANCE NAME,REPORTING THRESHOLD (kg),QUANTITY RELEASED (kg),ABOVE THRESHOLD,REGULATED INDUSTRY SECTOR,REGULATED INDUSTRY SUB SECTOR
0,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Benzo(a)pyrene,1.000000e+00,0.000,0.000,Water Industry,Water Industry
1,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Benzo(b)fluoranthene,1.000000e+00,0.000,0.000,Water Industry,Water Industry
2,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Octylphenols and octylphenol ethoxylates,1.000000e+00,0.000,0.000,Water Industry,Water Industry
3,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Air,Chloroform (Trichloromethane),1.000000e+02,0.000,0.000,Water Industry,Water Industry
4,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Trifluralin,1.000000e-03,0.000,0.000,Water Industry,Water Industry
5,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Carbon tetrachloride (Tetrachloromethane),1.000000e+00,0.000,0.000,Water Industry,Water Industry
6,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Chloroform (Trichloromethane),5.000000e+00,0.000,0.000,Water Industry,Water Industry
7,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Air,Carbon dioxide,1.000000e+07,0.000,0.000,Water Industry,Water Industry
8,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Dichloromethane (DCM) (Methylene chloride),1.000000e+01,0.000,0.000,Water Industry,Water Industry
9,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Organotin compounds - as Sn,5.000000e+00,0.000,0.000,Water Industry,Water Industry
10,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Phenols - total as C,2.000000e+01,0.000,0.000,Water Industry,Water Industry
11,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Lead,2.000000e+01,0.000,0.000,Water Industry,Water Industry
12,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Dioxins and furans (PCDDs/PCDFs) - as WHO TEQ,1.000000e-04,0.000,0.000,Water Industry,Water Industry
13,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Dioxins and furans (PCDDs/PCDFs) - as ITEQ,1.000000e-04,0.000,0.000,Water Industry,Water Industry
14,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Air,Ammonia,1.000000e+03,0.000,0.000,Water Industry,Water Industry
15,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,"Brominated diphenylethers - penta-, octa- and ...",1.000000e-01,0.000,0.000,Water Industry,Water Industry
16,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Chlorides - as Cl,2.000000e+06,0.000,0.000,Water Industry,Water Industry
17,2013,01229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Air,Methane,1.000000e+04,0.000,0.000,Water Industry,Water Industry
18,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Nonylphenols and nonylphenol ethoxylates,1.000000e+00,41.000,40.000,Water Industry,Water Industry
19,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Naphthalene,1.000000e+00,17.100,16.100,Water Industry,Water Industry
20,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Tributyltin and compounds - as TBT,5.000000e-03,0.011,0.006,Water Industry,Water Industry
21,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Mercury,1.000000e-01,0.420,0.320,Water Industry,Water Industry
22,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Nickel,2.000000e+01,382.000,362.000,Water Industry,Water Industry
23,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Cyanides - as CN,5.000000e+01,163.000,113.000,Water Industry,Water Industry
24,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Fluorides - as F,2.000000e+03,3640.000,1640.000,Water Industry,Water Industry
25,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Zinc,1.000000e+02,977.000,877.000,Water Industry,Water Industry
26,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Di(2-ethylhexyl)phthalate (DEHP),1.000000e-01,29.700,29.600,Water Industry,Water Industry
27,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Diuron,5.000000e-02,1.550,1.500,Water Industry,Water Industry
28,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Halogenated organic compounds - as AOX,1.000000e+03,1730.000,730.000,Water Industry,Water Industry
29,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Nitrogen - as total N,5.000000e+04,335000.000,285000.000,Water Industry,Water Industry

In [13]:
prediction_dataset_df = dataset_df[ (dataset_df['SITE POSTCODE'] == 'EX2 7AA') & (dataset_df['SUBSTANCE NAME'] == 'Nitrogen - as total N') ]
#prediction_dataset_df = dataset_df[ dataset_df['SITE POSTCODE'] == 'EX2 7AA' ]
#prediction_dataset_df = dataset_df[ (dataset_df['YEAR'] == 2013 ) & (dataset_df['SUBSTANCE NAME'] == 'Nonylphenols and nonylphenol ethoxylates') ]

prediction_dataset_df.head(60)

,YEAR,AUTHORISATION ID / PERMIT ID,OPERATOR NAME,SITE ADDRESS,SITE POSTCODE,EA AREA NAME,ROUTE NAME,SUBSTANCE NAME,REPORTING THRESHOLD (kg),QUANTITY RELEASED (kg),ABOVE THRESHOLD,REGULATED INDUSTRY SECTOR,REGULATED INDUSTRY SUB SECTOR
29,2013,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Nitrogen - as total N,50000.0,335000.0,285000.0,Water Industry,Water Industry
34791,2014,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Nitrogen - as total N,50000.0,358000.0,308000.0,Water Industry,Water Industry
86195,2015,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,Devon and Cornwall,Controlled Waters,Nitrogen - as total N,50000.0,332000.0,282000.0,Water Industry,Water Industry
108050,2016,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,"Devon, Cornwall and the Isles of Scilly",Controlled Waters,Nitrogen - as total N,50000.0,343000.0,293000.0,Water Industry,Water Industry
146008,2017,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,"Devon, Cornwall and the Isles of Scilly",Controlled Waters,Nitrogen - as total N,50000.0,335000.0,285000.0,Water Industry,Water Industry
166710,2018,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,"Devon, Cornwall and the Isles of Scilly",Controlled Waters,Nitrogen - as total N,50000.0,392000.0,342000.0,Water Industry,Water Industry
196628,2019,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,"Devon, Cornwall and the Isles of Scilly",Controlled Waters,Nitrogen - as total N,50000.0,368000.0,318000.0,Water Industry,Water Industry
229502,2020,001229,SOUTH WEST WATER LTD,EXETER STW (Countess Wear),EX2 7AA,"Devon, Cornwall and the Isles of Scilly",Controlled Waters,Nitrogen - as total N,50000.0,376000.0,326000.0,Water Industry,Water Industry

In [14]:
new_dataset = pd.DataFrame()

In [15]:
dataset_df.columns

Index(['YEAR', 'AUTHORISATION ID / PERMIT ID', 'OPERATOR NAME', 'SITE ADDRESS',
       'SITE POSTCODE', 'EA AREA NAME', 'ROUTE NAME', 'SUBSTANCE NAME',
       'REPORTING THRESHOLD (kg)', 'QUANTITY RELEASED (kg)', 'ABOVE THRESHOLD',
       'REGULATED INDUSTRY SECTOR', 'REGULATED INDUSTRY SUB SECTOR'],
      dtype='object')

In [16]:
dataset_df.describe()

,YEAR,REPORTING THRESHOLD (kg),QUANTITY RELEASED (kg),ABOVE THRESHOLD
count,261248.000000,2.612480e+05,2.612480e+05,2.612480e+05
mean,2016.459590,4.339815e+05,4.589669e+06,4.438817e+06
std,2.304581,2.531137e+06,1.597689e+08,1.595216e+08
min,2013.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,2014.000000,1.000000e+00,0.000000e+00,0.000000e+00
50%,2016.000000,1.000000e+02,0.000000e+00,0.000000e+00
75%,2018.000000,1.000000e+04,2.600000e-01,6.000000e-04
max,2020.000000,1.000000e+08,2.374538e+10,2.373538e+10

In [17]:
dataset_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261248 entries, 0 to 261247
Data columns (total 13 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   YEAR                           261248 non-null  int64
 1   AUTHORISATION ID / PERMIT ID   261248 non-null  object
 2   OPERATOR NAME                  261248 non-null  object
 3   SITE ADDRESS                   261248 non-null  object
 4   SITE POSTCODE                  248105 non-null  object
 5   EA AREA NAME                   261248 non-null  object
 6   ROUTE NAME                     261248 non-null  object
 7   SUBSTANCE NAME                 261248 non-null  object
 8   REPORTING THRESHOLD (kg)       261248 non-null  float64
 9   QUANTITY RELEASED (kg)         261248 non-null  float64
 10  ABOVE THRESHOLD                261248 non-null  float64
 11  REGULATED INDUSTRY SECTOR      261248 non-null  object
 12  REGULATED INDUSTRY SUB SECTOR  261225 non-null  object
dtypes: float64(3), int64(1), object(9)
memory usage: 25.9+ MB

In [18]:
dataset_df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
261243    False
261244    False
261245    False
261246    False
261247    False
Length: 261248, dtype: bool

In [19]:
sum(dataset_df.duplicated())

0

In [20]:
dataset_df.isnull().sum()

YEAR                                 0
AUTHORISATION ID / PERMIT ID         0
OPERATOR NAME                        0
SITE ADDRESS                         0
SITE POSTCODE                    13143
EA AREA NAME                         0
ROUTE NAME                           0
SUBSTANCE NAME                       0
REPORTING THRESHOLD (kg)             0
QUANTITY RELEASED (kg)               0
ABOVE THRESHOLD                      0
REGULATED INDUSTRY SECTOR            0
REGULATED INDUSTRY SUB SECTOR       23
dtype: int64

In [21]:
modifieddata=dataset_df.dropna()

In [22]:
dataset_df.isnull().sum()

YEAR                                 0
AUTHORISATION ID / PERMIT ID         0
OPERATOR NAME                        0
SITE ADDRESS                         0
SITE POSTCODE                    13143
EA AREA NAME                         0
ROUTE NAME                           0
SUBSTANCE NAME                       0
REPORTING THRESHOLD (kg)             0
QUANTITY RELEASED (kg)               0
ABOVE THRESHOLD                      0
REGULATED INDUSTRY SECTOR            0
REGULATED INDUSTRY SUB SECTOR       23
dtype: int64

In [23]:
dataset_df.to_excel("C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Consolidated Data.xlsx", index=False)

In [30]:
dataset_df.to_excel("C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Consolidated Data.xlsx")
dataset_df.dropna(inplace = True)

In [31]:
dataset_df.to_excel("C:\\Users\\admin\\OneDrive\\Desktop\\Dissertation\\Consolidated Data.xlsx", index=False)

In [32]:
dataset_df.isnull().sum()

YEAR                             0
AUTHORISATION ID / PERMIT ID     0
OPERATOR NAME                    0
SITE ADDRESS                     0
SITE POSTCODE                    0
EA AREA NAME                     0
ROUTE NAME                       0
SUBSTANCE NAME                   0
REPORTING THRESHOLD (kg)         0
QUANTITY RELEASED (kg)           0
ABOVE THRESHOLD                  0
REGULATED INDUSTRY SECTOR        0
REGULATED INDUSTRY SUB SECTOR    0
dtype: int64